# Generated by Django 4.1.7 on 2023-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portell",
            name="winePicture",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
