# Generated by Django 4.1.7 on 2023-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_portell_winepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="portell",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
