# Generated by Django 4.1.7 on 2023-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_portell_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portell",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
