# Generated by Django 4.1.7 on 2023-08-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_portell_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home", models.CharField(max_length=255)),
                ("home_en", models.CharField(max_length=255, null=True)),
                ("home_pl", models.CharField(max_length=255, null=True)),
                ("about", models.CharField(max_length=255)),
                ("about_en", models.CharField(max_length=255, null=True)),
                ("about_pl", models.CharField(max_length=255, null=True)),
                ("wines", models.CharField(max_length=255)),
                ("wines_en", models.CharField(max_length=255, null=True)),
                ("wines_pl", models.CharField(max_length=255, null=True)),
                ("contact", models.CharField(max_length=255)),
                ("contact_en", models.CharField(max_length=255, null=True)),
                ("contact_pl", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("text_en", models.CharField(max_length=255, null=True)),
                ("text_pl", models.CharField(max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_pl", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_pl", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("text_en", models.CharField(max_length=255, null=True)),
                ("text_pl", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_pl", models.TextField(null=True)),
                ("caption", models.CharField(max_length=255)),
                ("caption_en", models.CharField(max_length=255, null=True)),
                ("caption_pl", models.CharField(max_length=255, null=True)),
                ("button", models.CharField(max_length=255)),
                ("button_en", models.CharField(max_length=255, null=True)),
                ("button_pl", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="portell",
            name="data",
        ),
        migrations.RemoveField(
            model_name="portell",
            name="winePicture",
        ),
        migrations.AddField(
            model_name="portell",
            name="alcohol",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="portell",
            name="alcohol_en",
            field=models.CharField(default="N/A", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="alcohol_pl",
            field=models.CharField(default="N/A", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="description_pl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="wines/"),
        ),
        migrations.AddField(
            model_name="portell",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="name_pl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="type",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="portell",
            name="type_en",
            field=models.CharField(default="N/A", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="type_pl",
            field=models.CharField(default="N/A", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="variety",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="portell",
            name="variety_en",
            field=models.CharField(default="N/A", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portell",
            name="variety_pl",
            field=models.CharField(default="N/A", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="portell",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="portell",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
